apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: microservice-trigger-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.resource.repository.id)
  - name: git-repo-name
    value: $(body.resource.repository.name)
  - name: git-revision
    value: $(body.resource.commits[0].commitId)
  - name: git-pushid
    value: $(body.resource.pushId)
