apiVersion: v1
kind: Service
metadata:
  name: login-microservice-svc
  namespace: grahasti
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: login-microservice
