apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: abhishekvishnoi
  password: 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