apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: login-microservice-trigger-template
spec:
  params:
  - name: git-repo-name
  - name: git-repo-url
  - name: git-revision
  - name: git-pushid
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations: {}
      generateName: login-microservice-pipeline-$(tt.params.git-pushid)-
      labels:
        tekton.dev/pipeline: login-microservice-pipeline
      namespace: lotp
    spec:
      serviceAccountName: pipeline-run-sa
      params:
      - name: git-repo-name
        value: $(tt.params.git-repo-name)
      - name: git-repo-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: git-pushid
        value: $(tt.params.git-pushid)
      pipelineRef:
        name: login-microservice-pipeline
      resources: []
      status: null
      workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: trigger2
