apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login-microservice
  name: login-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-microservice
  template:
    metadata:
      labels:
        app: login-microservice
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/lotp/login-microservice-is:002
        imagePullPolicy: Always
        name: login-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: login-microservice-config