apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui-microservice
  name: ui-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-microservice
  template:
    metadata:
      labels:
        app: ui-microservice
    spec:
      containers:
      - image: quay.io/abvishno/oc-pipelines-ui-microservice
        imagePullPolicy: Always
        name: ui-microservice
        ports:
        - containerPort: 8080
          protocol: TCP

