apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-microservice
  name: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
      - image: docker.io/abhishekkvvishnoi/lotp-users-microservice:002
        imagePullPolicy: Always
        name: users-microservice
        ports:
        - containerPort: 8082
          protocol: TCP