apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-build
spec:
  description: |-
    This task can be used to run npm goals on a project.
    This task can be used to run npm goals on a project where package.json is present and has some pre-defined npm scripts.
  params:
  - default: .
    description: The path where package.json of the project is defined.
    name: PATH_CONTEXT
    type: string
  - default:
    - run
    - build
    - --prod
    description: The npm goals you want to run.
    name: ARGS
    type: array
  steps:
  - args:
    - npm install
    command:
    - /bin/sh
    - -c
    image: node:16-buster
    name: npm-install
    resources: {}
    workingDir: /workspace/output
  - args:
    - npm run build
    command:
    - /bin/sh
    - -c
    image: node:16-buster
    name: npm-build
    resources: {}
    workingDir: /workspace/output
  workspaces:
  - name: output
