apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: account-microservice-pipeline
spec:
  params:
  - default: xxxxx
    description: Reference of the image buildah will produce.
    name: git-pushid
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: https://github.com/Lord-of-the-Pods/account-microservice.git
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "false"
    - name: deleteExisting
      value: "true"
    - name: verbose
      value: "true"
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: maven-build
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: maven-build
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: buildah
    params:
    - name: IMAGE
      value: docker.io/abhishekkvvishnoi/lotp-account-microservice
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "false"
    - name: FORMAT
      value: oci
    runAfter:
    - maven-build
    taskRef:
      kind: Task
      name: buildah
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: buildah-tag
    params:
    - name: IMAGE
      value: docker.io/abhishekkvvishnoi/lotp-account-microservice:$(params.git-pushid)
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "false"
    - name: FORMAT
      value: oci
    runAfter:
    - maven-build
    taskRef:
      kind: Task
      name: buildah
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: update-deployment
    params:
    - name: deployment
      value: account-microservice
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/lotp/account-microservice-is:$(params.git-pushid)
    runAfter:
    - buildah-tag
    taskRef:
      kind: Task
      name: update-deployment
  - name: gitops-task
    params:
      - name: configGitUrl
        value: >-
          https://github.com/Lord-of-the-Pods/lotp-cicd-minikube.git
      - name: path
        value: yamls/Openshift/Deployments
      - name: fileName
        value: account-microservice.yaml
      - name: imageName
        value: >-
          image-registry.openshift-image-registry.svc:5000/lotp/account-microservice-is:$(params.git-pushid)
      - name: userName
        value: vishnoi.abhishek
      - name: userEmail
        value: vishnoi.abhishek@hotmail.com
    runAfter:
      - update-deployment
    taskRef:
      kind: Task
      name: gitops-task
    workspaces:
      - name: gitops-workspace
        workspace: shared-workspace

  workspaces:
  - name: shared-workspace
